spring:
  application:
    name: simple-ecommerce-application

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.springframework.security: Debug