spring:
  application:
    name: simple-ecommerce-application
    file:
      upload:
        file-upload-path: ./uploads

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2MB

logging:
  level:
    org.springframework.security: Debug
